### ISSUE TITLE
S-1 작업

### ISSUE THREAD

**Issue by jaemin1005** [jaemin1005/Team.gg#6]

**Comment by jaemin1005** [comment]
검색창 Debounce 모듈 테스트

**Comment by eonduck2** [comment]
# S-1 Debounce 적용

1. CJS 방식으로 구현된 Debounce.js, Time,js module들 Client Side에서 호환 불가능 => JS 파일 내 module, ESM 방식으로 변경
2. ESM 방식으로 import된 time 접근 시 GetTime  Method 관련 오류 확인 -> 정적 필드 선언 후, 객체로서 접근하는 방식으로 수정
3. 그에 따라 ESM 방식의 debounec.js도 약간의 변동 사항 있음.(import&&export, GetTime Method 접근)

- 확인 후, CJS 방식의 Debounce.js파일이나, 기능 관련 더 이상 쓰이지 않는 코드 삭제 필요
- 가장 최근 team.gg 파일 pull 후 작업 진행, server.js에서 JSON 관련 error 때문에 기존 서버 실행 불가 
-> index.html에서 live server를 통해 작업했기 때문에 반드시 호환성 확인 후, Issue6 Branch 확인하고 Pull Request 통해 merge 필요
